### PR TITLE
Add example from dash-sample-apps

### PR DESCRIPTION
**Pull request by abhishalya**
This adds dashboards implementation of an example
from dash-sample-apps. The example used here is
dash-financial-report. The current implmentation is
only for the 'Overview' page of the app.

### CODE REVIEW

**Comment by abhishalya** [comment]
Now also deployed on https://financial-report-dashboards.herokuapp.com/

(It takes some time to load)

**Review by logankilpatrick — APPROVED** [review]
Great work!

**Comment by aviks** [comment]
This is cool! Would be good to enhance this with some behaviour -- ie, click on something to make something happen.

**Comment by abhishalya** [comment]
@aviks Thanks! Will try to update this one :)

**Pull request merged**
