### PR TITLE
Added a new example

### PR DESCRIPTION
**Pull request by TheComputerM**
This new example is a graph regarding study time vs marks scored.

### CODE REVIEW

**Review by logankilpatrick — COMMENTED** [review]
Hey @TheComputerM Please be sure to add proper attribution to each file. You currently have attribution on only one file. This implies that all other work is original and of your own doing. If you referenced or used any other sources, please add those to the respective file that they were used to help make.

**Comment by TheComputerM** [comment]
So can I add attribution in the form of comments in my script file?

**Comment by logankilpatrick** [comment]
Awesome!

**Comment by TheComputerM** [comment]
Can you approve my task?

**Review by logankilpatrick — APPROVED** [review]
Looks good! Nice job.

**Comment by TheComputerM** [comment]
Thanks

**Pull request merged**
